steps:
    # Install dependencies and build
    - name: "node:20-alpine"
      entrypoint: "sh"
      args:
          - "-c"
          - |
              npm ci
              npm run build

    # Build Docker image with optimized Dockerfile
    - name: "gcr.io/cloud-builders/docker"
      args:
          - "build"
          - "-f"
          - "docker/Dockerfile"
          - "-t"
          - "${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/tbe-api:${SHORT_SHA}"
          - "."

    # Push Docker image
    - name: "gcr.io/cloud-builders/docker"
      args:
          - "push"
          - "${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/tbe-api:${SHORT_SHA}"

    # Deploy to Cloud Run
    - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
      entrypoint: "gcloud"
      args:
          - "run"
          - "deploy"
          - "${_SERVICE_NAME}"
          - "--image"
          - "${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/tbe-api:${SHORT_SHA}"
          - "--region"
          - "${_REGION}"
          - "--platform"
          - "managed"
          - "--allow-unauthenticated"
          - "--memory"
          - "${_MEMORY}"
          - "--cpu"
          - "1"
          - "--min-instances"
          - "${_MIN_INSTANCES}"
          - "--max-instances"
          - "${_MAX_INSTANCES}"
          - "--concurrency"
          - "80"
          - "--timeout"
          - "300s"
          - "--port"
          - "3000"
          - "--set-env-vars"
          - "NODE_ENV=${_ENVIRONMENT}"
          - "--set-secrets"
          - "MONGODB_URI=mongodb-uri:latest,NEXTAUTH_SECRET=nextauth-secret:latest,ADMIN_SECRET=admin-secret:latest,OPENAI_API_KEY=openai-api-key:latest,YOUTUBE_API_KEY=youtube-api-key:latest,CASHFREE_SECRET_KEY=cashfree-secret-key:latest,EMAIL_API_KEY=email-api-key:latest,SENTRY_AUTH_TOKEN=sentry-auth-token:latest"
          - "--quiet"

# Configure Cloud Build
options:
    logging: CLOUD_LOGGING_ONLY
    machineType: "E2_HIGHCPU_8"

# Substitution variables
substitutions:
    _REGION: "asia-south1"
    _REPOSITORY: "tbe-api-repo"
    _SERVICE_NAME: "tbe-api-staging"
    _ENVIRONMENT: "staging"
    _MEMORY: "1Gi"
    _MIN_INSTANCES: "0"
    _MAX_INSTANCES: "10"
